version: 0.2
phases:
  install:
    commands:
      - pip install yq
      - pip install boto3
  pre_build:
    commands:
      - echo "Initiating ClixxApp deployment"
      - echo "Additional setup commands as needed"
  build:
    on-failure: ABORT
    commands:
      - echo Build initiation `date`
      - echo "Setting up ClixxApp Security Group and configuring components"
      - |

          deployment_flag='destroy'  # Modify as needed, e.g., set via environment variable

          if [[ $deployment_flag == 'destroy' ]]; then
            echo "Restoring ClixxApp database instance from snapshot..."
            python destroy_CliXX.py
          elif [[ $deployment_flag == 'destroy' ]]; then
            echo "Deleting ClixxApp resources..."
            python destroy_clixx.py
          fi

          # deployment_flag='create'  # Define dynamically as needed

          # if [[ $deployment_flag == 'create' ]]; then
          #   echo "Restoring ClixxApp database instance from snapshot..."
          #   python create_clixx.py
            
          #  fi

  post_build:
    commands:
      - echo Build completed successfully `date`
