version: 0.2
phases:
  install:
    commands:
      - pip install yq
      - pip install boto3
  pre_build:
    commands:
      - echo "Initiating ClixxApp deployment"
      - echo "Additional setup commands as needed"
  build:
    on-failure: ABORT
    commands:
      - echo Build initiation `date`
      - echo "Setting up ClixxApp Security Group and configuring components"
      - |
          deployment_flag='destroy'  # Define dynamically as needed

          if [[ $deployment_flag == 'destro' ]]; then
            echo "Restoring ClixxApp database instance from snapshot..."
            python destroy_CliXX.py
            
          # elif [[ $deployment_flag == 'destroy_Clixx.py' ]]; then
          #   echo "Deploying ClixxApp environment..."
          #   python deploy_clixxapp_env.py

          # elif [[ $deployment_flag == 'configure_fs' ]]; then
          #   echo "Configuring ClixxApp on File System (FS)..."
          #   python configure_clixxapp_fs.py

          # elif [[ $deployment_flag == 'deploy_custom' ]]; then
          #   echo "Deploying custom ClixxApp configuration on VPC..."
          #   python deploy_clixxapp_custom_vpc.py

          # elif [[ $deployment_flag == 'destroy_Clixx.py' ]]; then
          #   echo "Removing ClixxApp environment..."
          #   python delete_clixxapp_env.py

          # elif [[ $deployment_flag == 'delete_custom' ]]; then
          #   echo "Deleting custom ClixxApp configuration on VPC..."
          #   python delete_clixxapp_custom_vpc.py

          # elif [[ $deployment_flag == 'assume_role' ]]; then
          #   echo "Initiating role assumption for ClixxApp operations..."
          #   python assume_clixx_role.py

          # else
          #   echo "Invalid option. Please reset the deployment_flag."
          fi

  post_build:
    commands:
      - echo Build completed successfully `date`
