version: 0.2
phases:
  install:
    commands:
      - pip install yq
      - pip install boto3
  pre_build:
    commands:
      - echo "Starting CliXX deployment"
      - echo "more commands"
  build:
    on-failure: ABORT
    commands:
      - deployment_flag="destroy"
      - if [[ $deployment_flag == 'destroy' ]]; then
          python destroy_CliXX.py;
        elif [[ $deployment_flag == 'create' ]]; then
          python create_clixx.py;
        fi
  post_build:
    commands:
      - echo "Build completed on $(date)"
